name: Build binary for release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude: # Exclude unsupported combinations
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Or use go-version-file: 'go.mod'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          go build -o build/clash-subscription-updater-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Only create release on tag push
        with:
          tag_name: ${{ github.ref_name }} # Uses the pushed tag name as the release tag
          name: Release ${{ github.ref_name }} # Sets the release name
          draft: false # Set to true to create a draft release
          prerelease: false # Set to true for a pre-release
          files: |
            build/* # Upload all compiled binaries